[default]
ALLOWED_ORIGINS = ["http://localhost:3000", "https://smart-ktx.netlify.app/"]
MONGO_DSN = "mongodb://localhost:27017/ktx_bk"
JWT_SECRET_KEY = "78DBDE372E7932A18B891BB69D118"
JWT_ALGORITHM = "HS256"